---
all:
  children:
    web:
      hosts:
        prod-web-01:
          ansible_host: 10.30.10.11
        prod-web-02:
          ansible_host: 10.30.10.12
    app:
      hosts:
        prod-app-01:
          ansible_host: 10.30.10.21
        prod-app-02:
          ansible_host: 10.30.10.22
