---
- hosts: locakhost
  become: yes
  vars:
    target_service: httpd
  tasks:
    - name: install software
      block:          # Run time information to collect information
        - service:
            name: "{{ target_service }}"
            state: started
          register: service_status
      rescue:
        - debug:
            var: service_status
      always:
        - debug:
            msg: "Tried to ensure service was running"
